### ISSUE TITLE
wrong comparePath

### ISSUE THREAD

**Issue by lolow** [jackjackk/gdxcompare#4]

**Comment by jackjackk** [comment]
I cannot reproduce! it should be opening the compare.html inside the same path of installation of gdxcompare, which in my case is anaconda/lib/site-packages/gdxcompare. You can check the installed files with: 
```
python -m pip show -f gdxcompare
```
what value is comparePath getting assigned to?

**Comment by lolow** [comment]
now it is working after a reinstall.
thanks!
